# Generated by Django 4.1.7 on 2023-12-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeputyHeadboy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('position', models.CharField(max_length=30, verbose_name='Position')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DeputyHeadirl',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('position', models.CharField(max_length=30, verbose_name='Position')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DeputySportsboy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('position', models.CharField(max_length=30, verbose_name='Position')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DeputySportsgirl',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('position', models.CharField(max_length=30, verbose_name='Position')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Headboy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('position', models.CharField(max_length=30, verbose_name='Position')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Headirl',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('position', models.CharField(max_length=30, verbose_name='Position')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sportsboy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('position', models.CharField(max_length=30, verbose_name='Position')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sportsgirl',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('position', models.CharField(max_length=30, verbose_name='Position')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('deputyheadboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deputyheadboy')),
                ('deputyheadgirl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deputyheadirl')),
                ('deputysportsboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deputysportsboy')),
                ('deputysportsgirl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deputysportsgirl')),
                ('headboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.headboy')),
                ('headgirl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.headirl')),
                ('sportsboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sportsboy')),
                ('sportsgirl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sportsgirl')),
            ],
        ),
    ]
