# Generated by Django 4.1.7 on 2023-12-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestants',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('position', models.CharField(max_length=30, verbose_name='Position')),
                ('photo', models.ImageField(upload_to='')),
                ('votes', models.IntegerField(verbose_name='Votes')),
            ],
        ),
        migrations.RemoveField(
            model_name='votes',
            name='deputyheadboy',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='deputyheadgirl',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='deputysportsboy',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='deputysportsgirl',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='headboy',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='headgirl',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='sportsboy',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='sportsgirl',
        ),
        migrations.DeleteModel(
            name='DeputyHeadboy',
        ),
        migrations.DeleteModel(
            name='DeputyHeadirl',
        ),
        migrations.DeleteModel(
            name='DeputySportsboy',
        ),
        migrations.DeleteModel(
            name='DeputySportsgirl',
        ),
        migrations.DeleteModel(
            name='Headboy',
        ),
        migrations.DeleteModel(
            name='Headirl',
        ),
        migrations.DeleteModel(
            name='Sportsboy',
        ),
        migrations.DeleteModel(
            name='Sportsgirl',
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
