# Generated by Django 4.1.7 on 2024-04-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contestants_remove_votes_deputyheadboy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('jssid', models.CharField(max_length=10, verbose_name='JSSID')),
            ],
        ),
        migrations.AlterField(
            model_name='contestants',
            name='photo',
            field=models.ImageField(upload_to='contestants/'),
        ),
    ]
