# Generated by Django 4.1.7 on 2024-04-15 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_students_remove_votes_jssid_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='contestant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contestant', to='core.contestants'),
        ),
        migrations.AddField(
            model_name='votes',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='core.students'),
        ),
    ]
