# Generated by Django 4.1.7 on 2024-04-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_votes_contestant_votes_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='contestant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contestant', to='core.contestants'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='core.students'),
        ),
    ]
