# Generated by Django 4.1.7 on 2024-04-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_votes_contestant_alter_votes_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='grade_sec',
            field=models.CharField(default='', max_length=3, verbose_name='Grade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
