# Generated by Django 4.1.7 on 2024-04-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_students_grade_sec_alter_history_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="votes",
            name="email",
            field=models.CharField(default="", max_length=50, verbose_name="Email"),
            preserve_default=False,
        ),
    ]
