# Generated by Django 4.1.7 on 2024-04-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_votes_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="email",
            field=models.CharField(default="", max_length=50, verbose_name="Email"),
            preserve_default=False,
        ),
    ]
