# Generated by Django 4.1.7 on 2024-04-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_history_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="jssid",
        ),
        migrations.RemoveField(
            model_name="history",
            name="student_name",
        ),
        migrations.RemoveField(
            model_name="votes",
            name="student",
        ),
        migrations.DeleteModel(
            name="Students",
        ),
    ]
